spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/products_db
    username: harshil
    password: harshil8705
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: postgresql
    show-sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
    baseline-description: "init"
    url: jdbc:postgresql://localhost:5432/products_db
    user: harshil
    password: harshil8705

server:
  port: 8050